version: '3.8'

services:
  mysql:
    platform: linux/amd64
    image: mysql:8.0.36-debian
    container_name: tse-mysql
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: tse_db
      MYSQL_USER: tse_user
      MYSQL_PASSWORD: tse_tse
    volumes:
      - tse_mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  tse_mysql_data:
