version: '3.8'

services:
  reverse_proxy:
    image: ${IMAGE_REPO}/reverse_proxy:${VERSION}
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

  frontend:
    image: ${IMAGE_REPO}/frontend:${VERSION}
    container_name: tse-frontend
    ports:
      - "3000:3000"
    restart: unless-stopped

  backend:
    image: ${IMAGE_REPO}/backend:${VERSION}
    container_name: tse-backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "5001:5001"
    volumes:
      - uploadsFiles:/app/uploads
    restart: unless-stopped

volumes:
  uploadsFiles:
